// Bao M0 spike — capture + deterministic replay on a single page.
// No LLM, no backend, no cross-navigation. Proves the risky core:
// selector generation, multi-selector fallback resolution, and the input actuator.

(() => {
  "use strict";

  // Idempotent: the manifest auto-injects this, but the harness may also inject
  // it programmatically (chrome.scripting) as a readiness fallback. Bail on a
  // second run so we don't register a duplicate onMessage listener.
  if (window.__baoM0Loaded) return;
  window.__baoM0Loaded = true;

  // ---------- shared helpers ----------
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const esc = (s) => (window.CSS && CSS.escape ? CSS.escape(s) : s.replace(/[^a-zA-Z0-9_-]/g, "\\$&"));

  function isTextField(el) {
    return el instanceof HTMLTextAreaElement ||
      (el instanceof HTMLInputElement &&
        !["checkbox", "radio", "button", "submit", "file", "range"].includes(el.type));
  }

  function isVisible(el) {
    const r = el.getBoundingClientRect();
    if (r.width === 0 && r.height === 0) return false;
    const s = getComputedStyle(el);
    return s.visibility !== "hidden" && s.display !== "none";
  }

  // IDs like "ember123", ":r1:", "mui-3481", "radix-:r0:", uuids → unstable, skip.
  function looksAutoGenerated(id) {
    return /\d{3,}/.test(id) || /[:]/.test(id) || /^[a-f0-9]{8}-/.test(id) || /^[a-z]+-?\d+$/i.test(id);
  }

  function implicitRole(el) {
    const tag = el.nodeName.toLowerCase();
    if (tag === "button") return "button";
    if (tag === "a" && el.hasAttribute("href")) return "link";
    if (tag === "select") return "combobox";
    if (tag === "textarea") return "textbox";
    if (tag === "input") {
      const t = (el.getAttribute("type") || "text").toLowerCase();
      if (["checkbox"].includes(t)) return "checkbox";
      if (["radio"].includes(t)) return "radio";
      if (["submit", "button"].includes(t)) return "button";
      return "textbox";
    }
    return el.getAttribute("role") || null;
  }

  // Approximate accessible name (good enough for M0).
  function accName(el) {
    const aria = el.getAttribute("aria-label");
    if (aria) return aria.trim();
    if (el.getAttribute("placeholder")) return el.getAttribute("placeholder").trim();
    if (el.labels && el.labels[0]) return el.labels[0].textContent.trim();
    if (el.value && (el.type === "submit" || el.type === "button")) return el.value.trim();
    const txt = (el.textContent || "").replace(/\s+/g, " ").trim();
    return txt.slice(0, 80);
  }

  // ---------- selector generation (ranked, multi-candidate) ----------
  function getSelectors(el) {
    const sels = [];
    for (const attr of ["data-testid", "data-test", "data-cy", "data-qa"]) {
      const v = el.getAttribute(attr);
      if (v) sels.push({ type: "testid", value: `[${attr}="${esc(v)}"]`, score: 0.95 });
    }
    const role = implicitRole(el);
    const name = accName(el);
    if (role && name && name.length <= 60) {
      sels.push({ type: "aria", value: JSON.stringify({ role, name }), score: 0.9 });
    }
    if (name && ["button", "link"].includes(role)) {
      sels.push({ type: "text", value: name, score: 0.7 });
    }
    if (el.id && !looksAutoGenerated(el.id)) {
      sels.push({ type: "id", value: `#${esc(el.id)}`, score: 0.8 });
    }
    sels.push({ type: "css", value: cssPath(el), score: 0.3 });
    return sels.sort((a, b) => b.score - a.score);
  }

  function cssPath(el) {
    const parts = [];
    while (el && el.nodeType === 1 && el !== document.body) {
      if (el.id && !looksAutoGenerated(el.id)) { parts.unshift(`#${esc(el.id)}`); break; }
      let nth = 1, sib = el;
      while ((sib = sib.previousElementSibling)) if (sib.nodeName === el.nodeName) nth++;
      parts.unshift(`${el.nodeName.toLowerCase()}:nth-of-type(${nth})`);
      el = el.parentElement;
    }
    return parts.join(" > ");
  }

  // ---------- capture-time anchoring (escalate context until unique) ----------
  // Extract a *stable* token from an href: a note/comment id (`c-12345`), a post
  // slug (`/p/foo`), or any path segment carrying digits. Query-string junk and
  // session ids are skipped by preferring these shapes.
  function stableHrefId(href) {
    if (!href) return null;
    const m = href.match(/c-\d+/) || href.match(/\/p\/[\w-]+/) || href.match(/\/[\w-]*\d[\w-]*/);
    return m ? m[0] : null;
  }
  // A selector that identifies a NODE by its own attributes, only if unique on page.
  function nodeUniqueSelector(node) {
    if (node.id && !looksAutoGenerated(node.id)) {
      const sel = `#${esc(node.id)}`;
      if (document.querySelectorAll(sel).length === 1) return sel;
    }
    for (const attr of ["data-testid", "data-test", "data-cy", "data-qa"]) {
      const v = node.getAttribute(attr);
      if (v) {
        const sel = `[${attr}="${esc(v)}"]`;
        if (document.querySelectorAll(sel).length === 1) return sel;
      }
    }
    return null;
  }
  // The smallest distinguishing signature inside `node`'s subtree: a unique link id.
  function uniqueHrefIn(node) {
    for (const a of node.querySelectorAll("a[href]")) {
      const id = stableHrefId(a.getAttribute("href"));
      if (id && document.querySelectorAll(`a[href*="${id.replace(/"/g, '\\"')}"]`).length === 1) return id;
    }
    return null;
  }
  // Last-resort signature for cards that carry no stable id/href (image-only
  // restacks, etc.): a short text fingerprint whose *exact* occurrences all live
  // inside `node` — i.e. unique to this card. Skips the target's own text and any
  // text it shares with sibling cards ("Like", "Reply", …).
  const normText = (el) => (el.textContent || "").replace(/\s+/g, " ").trim();
  function uniqueTextIn(node, leaf) {
    const seen = new Set();
    for (const el of node.querySelectorAll("*")) {
      if (el === leaf || el.contains(leaf) || leaf.contains(el)) continue;
      const t = normText(el);
      if (t.length < 3 || t.length > 80 || seen.has(t)) continue;
      seen.add(t);
      const exact = Array.from(document.querySelectorAll("*")).filter((e) => normText(e) === t);
      if (exact.length && exact.every((e) => node.contains(e))) return t;
    }
    return null;
  }

  // Walk up from the target to the nearest ancestor we can pin down uniquely, and
  // describe the target *within* it. This is what turns an ambiguous "Share" into
  // "the Share button inside the card linking to c-276371955".
  function buildAnchor(leaf) {
    let node = leaf.parentElement;
    for (let hops = 0; node && node !== document.body && hops < 15; hops++, node = node.parentElement) {
      const sel = nodeUniqueSelector(node);
      if (sel) return { node, descriptor: { kind: "selector", value: sel } };
      const href = uniqueHrefIn(node);
      if (href) return { node, descriptor: { kind: "href", id: href } };
      const txt = uniqueTextIn(node, leaf);
      if (txt) return { node, descriptor: { kind: "text", id: txt } };
    }
    return null;
  }
  // A css path from `root` down to `leaf` (root exclusive). Stable while the card's
  // *internal* structure holds, even as the feed around it reorders.
  function relPath(root, leaf) {
    const parts = [];
    let el = leaf;
    while (el && el !== root && el.nodeType === 1) {
      let nth = 1, sib = el;
      while ((sib = sib.previousElementSibling)) if (sib.nodeName === el.nodeName) nth++;
      parts.unshift(`${el.nodeName.toLowerCase()}:nth-of-type(${nth})`);
      el = el.parentElement;
    }
    return el === root ? parts.join(" > ") : null;
  }
  // A content-stable discriminator that singles `leaf` out from its same-named
  // siblings — its own attribute, independent of position.
  function refineWithin(matches, leaf) {
    for (const attr of ["data-testid", "data-test", "data-cy", "data-qa", "title", "name", "href"]) {
      const v = leaf.getAttribute(attr);
      if (v && matches.filter((m) => m.getAttribute(attr) === v).length === 1) return { attr, value: v };
    }
    return null;
  }
  function describeWithin(anchorNode, leaf) {
    const role = implicitRole(leaf);
    const name = accName(leaf);
    const matches = allByWithin({ role, name }, anchorNode);
    const within = { role, name, index: Math.max(0, matches.indexOf(leaf)) };
    // Only when the role+name is itself ambiguous inside the card do we need a
    // tiebreak: a distinguishing attribute first, a structural path second.
    if (matches.length > 1) {
      const attr = refineWithin(matches, leaf);
      if (attr) within.attr = attr;
      const rel = relPath(anchorNode, leaf);
      if (rel) within.rel = rel;
    }
    return within;
  }

  // True iff selector `s` resolves to exactly the captured element (same path replay
  // will take). If no robust selector is unique, we must anchor.
  function resolvesUniquelyTo(s, el) {
    const m = matchesOf(s);
    return m.length === 1 && m[0] === el;
  }

  // The recorded target: leaf selectors, plus an anchor + within-descriptor whenever
  // the leaf alone can't be resolved back to the exact element.
  function getTarget(el) {
    const selectors = getSelectors(el);
    const robustUnique = selectors.some((s) => s.type !== "css" && resolvesUniquelyTo(s, el));
    if (robustUnique) return { selectors, unique: true };

    const anchor = buildAnchor(el);
    if (anchor) {
      const within = describeWithin(anchor.node, el);
      return { selectors, anchor: anchor.descriptor, within, unique: true };
    }
    return { selectors, unique: false }; // best-effort: brittle css path only
  }

  // ---------- count-aware resolution ----------
  // Every resolver returns ALL matches (optionally scoped to a root subtree) so the
  // caller can reason about ambiguity instead of blindly taking the first hit — the
  // root cause of the "wrong item in a repeated list" bug.
  function allByAria({ role, name }, root = document) {
    return Array.from(root.querySelectorAll("*"))
      .filter((el) => implicitRole(el) === role && accName(el) === name);
  }
  function allByText(value, root = document) {
    return Array.from(root.querySelectorAll('button, a, [role="button"], input[type="submit"], summary'))
      .filter((el) => accName(el) === value);
  }
  function matchesOf(s, root = document) {
    try {
      if (["testid", "id", "css"].includes(s.type)) return Array.from(root.querySelectorAll(s.value));
      if (s.type === "aria") return allByAria(JSON.parse(s.value), root);
      if (s.type === "text") return allByText(s.value, root);
    } catch (_) {}
    return [];
  }
  // A selector "within" the anchor subtree: role+name, picked by recorded index.
  function allByWithin({ role, name }, root) {
    return Array.from(root.querySelectorAll("*"))
      .filter((el) => implicitRole(el) === role && (!name || accName(el) === name));
  }

  // ---------- anchor resolution (the robust path for repeated lists) ----------
  // Re-find the anchor's stable "seed" (a unique id'd container, or a unique link/
  // text deeper in the card), then climb to the smallest ancestor that actually
  // contains the target — content-anchored, so it survives feed reorders.
  function anchorSeed(a) {
    if (a.kind === "selector") return document.querySelector(a.value);
    if (a.kind === "href") return document.querySelector(`a[href*="${a.id.replace(/"/g, '\\"')}"]`);
    if (a.kind === "text") {
      const all = Array.from(document.querySelectorAll("*"));
      // Prefer an element whose exact text IS the fingerprint; fall back to any
      // element containing it. Smallest wins so the seed lands deep in one card.
      const exact = all.filter((el) => normText(el) === a.id);
      const pool = exact.length ? exact : all.filter((el) => (el.textContent || "").includes(a.id));
      return pool.sort((x, y) => x.textContent.length - y.textContent.length)[0] || null;
    }
    return null;
  }
  function resolveViaAnchor(target) {
    const seed = anchorSeed(target.anchor);
    if (!seed) return null;
    const within = target.within;
    let node = seed;
    for (let i = 0; i < 15 && node; i++) {
      const m = allByWithin(within, node);
      if (m.length) {
        if (m.length === 1) return m[0];
        // Collision inside the anchor: content-stable attribute beats structural
        // path beats raw positional index.
        if (within.attr) {
          const hit = m.find((el) => el.getAttribute(within.attr.attr) === within.attr.value);
          if (hit) return hit;
        }
        if (within.rel) { try { const r = node.querySelector(within.rel); if (r) return r; } catch (_) {} }
        return m[within.index] || m[0];
      }
      node = node.parentElement;
    }
    return null;
  }

  function resolveStep(target) {
    // 1) Anchor-scoped resolution wins — it's the only path that disambiguates one
    //    "Copy link" from its 20 identical siblings.
    if (target.anchor && target.within) {
      const el = resolveViaAnchor(target);
      if (el) return { el, via: "anchor" };
    }
    // 2) Plain selectors, but PREFER a uniquely-resolving one over first-of-many.
    //    A selector that matches the whole list must not outrank a precise one just
    //    because its `type` scores high.
    let ambiguous = null;
    for (const s of target.selectors) {
      const m = matchesOf(s);
      if (m.length === 1) return { el: m[0], via: s.type };
      if (m.length > 1 && !ambiguous) ambiguous = { el: m.find(isVisible) || m[0], via: `${s.type}~ambiguous` };
    }
    return ambiguous || { el: null };
  }
  async function waitForStep(target, timeout = 5000) {
    const start = Date.now();
    while (Date.now() - start < timeout) {
      const r = resolveStep(target);
      if (r.el && isVisible(r.el)) return r;
      await sleep(100);
    }
    return { el: null };
  }

  // ---------- the input actuator (the #1 silent killer) ----------
  function setNativeValue(el, value) {
    const proto = el instanceof HTMLTextAreaElement
      ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(proto, "value").set;
    setter.call(el, value);
    el.dispatchEvent(new InputEvent("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }

  // ---------- highlight overlay (the "watch it" feel) ----------
  function highlight(el) {
    const r = el.getBoundingClientRect();
    const box = document.createElement("div");
    Object.assign(box.style, {
      position: "fixed", left: r.left + "px", top: r.top + "px",
      width: r.width + "px", height: r.height + "px",
      border: "2px solid #e11", borderRadius: "3px", zIndex: 2147483647,
      pointerEvents: "none", boxShadow: "0 0 0 3px rgba(238,17,17,.25)",
      transition: "opacity .4s", opacity: "1",
    });
    document.documentElement.appendChild(box);
    setTimeout(() => { box.style.opacity = "0"; setTimeout(() => box.remove(), 400); }, 500);
  }

  // ---------- recording ----------
  let recording = false, steps = [], lastInputStep = null, lastInputEl = null;

  function humanLabel(action, el) {
    const name = accName(el) || el.nodeName.toLowerCase();
    return action === "input" ? `Type into "${name}"` : `Click "${name}"`;
  }
  function makeStep(action, el) {
    return { action, label: humanLabel(action, el), target: getTarget(el) };
  }

  function onClick(e) {
    const el = e.target.closest('button,a,[role="button"],input,select,summary,[onclick]') || e.target;
    lastInputEl = lastInputStep = null;
    steps.push(makeStep("click", el));
  }
  function onInput(e) {
    const el = e.target;
    if (!isTextField(el)) return;
    if (lastInputEl === el && lastInputStep) { lastInputStep.value = el.value; return; }
    const step = makeStep("input", el); step.value = el.value;
    steps.push(step); lastInputStep = step; lastInputEl = el;
  }

  function startRecording() {
    steps = []; lastInputEl = lastInputStep = null; recording = true;
    document.addEventListener("click", onClick, true);
    document.addEventListener("input", onInput, true);
  }
  function stopRecording() {
    recording = false;
    document.removeEventListener("click", onClick, true);
    document.removeEventListener("input", onInput, true);
    return steps;
  }

  // ---------- replay ----------
  async function replay(stepList) {
    const results = [];
    for (let i = 0; i < stepList.length; i++) {
      const step = stepList[i];
      const r = await waitForStep(step.target);
      if (!r.el) {
        results.push({ i, ok: false, reason: `Could not find: ${step.label}` });
        return { ok: false, failedAt: i, results }; // fail with clear report
      }
      highlight(r.el);
      r.el.scrollIntoView({ block: "center", behavior: "instant" });
      await sleep(150);
      if (step.action === "click") r.el.click();
      else if (step.action === "input") setNativeValue(r.el, step.value);
      results.push({ i, ok: true, via: r.via });
      await sleep(300);
    }
    return { ok: true, results };
  }

  // ---------- popup messaging ----------
  chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
    if (msg.cmd === "start-record") { startRecording(); sendResponse({ ok: true }); }
    else if (msg.cmd === "stop-record") { sendResponse({ steps: stopRecording() }); }
    else if (msg.cmd === "status") { sendResponse({ recording, count: steps.length }); }
    else if (msg.cmd === "replay") { replay(msg.steps).then(sendResponse); return true; }
    return true;
  });
})();
