// Bao M0 spike — capture + deterministic replay on a single page.
// No LLM, no backend, no cross-navigation. Proves the risky core:
// selector generation, multi-selector fallback resolution, and the input actuator.

(() => {
  "use strict";

  // Idempotent: the manifest auto-injects this, but the harness may also inject
  // it programmatically (chrome.scripting) as a readiness fallback. Bail on a
  // second run so we don't register a duplicate onMessage listener.
  if (window.__baoM0Loaded) return;
  window.__baoM0Loaded = true;

  // ---------- shared helpers ----------
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const esc = (s) => (window.CSS && CSS.escape ? CSS.escape(s) : s.replace(/[^a-zA-Z0-9_-]/g, "\\$&"));

  function isTextField(el) {
    return el instanceof HTMLTextAreaElement ||
      (el instanceof HTMLInputElement &&
        !["checkbox", "radio", "button", "submit", "file", "range"].includes(el.type));
  }

  function isVisible(el) {
    const r = el.getBoundingClientRect();
    if (r.width === 0 && r.height === 0) return false;
    const s = getComputedStyle(el);
    return s.visibility !== "hidden" && s.display !== "none";
  }

  // IDs like "ember123", ":r1:", "mui-3481", "radix-:r0:", uuids → unstable, skip.
  function looksAutoGenerated(id) {
    return /\d{3,}/.test(id) || /[:]/.test(id) || /^[a-f0-9]{8}-/.test(id) || /^[a-z]+-?\d+$/i.test(id);
  }

  function implicitRole(el) {
    const tag = el.nodeName.toLowerCase();
    if (tag === "button") return "button";
    if (tag === "a" && el.hasAttribute("href")) return "link";
    if (tag === "select") return "combobox";
    if (tag === "textarea") return "textbox";
    if (tag === "input") {
      const t = (el.getAttribute("type") || "text").toLowerCase();
      if (["checkbox"].includes(t)) return "checkbox";
      if (["radio"].includes(t)) return "radio";
      if (["submit", "button"].includes(t)) return "button";
      return "textbox";
    }
    return el.getAttribute("role") || null;
  }

  // Approximate accessible name (good enough for M0).
  function accName(el) {
    const aria = el.getAttribute("aria-label");
    if (aria) return aria.trim();
    if (el.getAttribute("placeholder")) return el.getAttribute("placeholder").trim();
    if (el.labels && el.labels[0]) return el.labels[0].textContent.trim();
    if (el.value && (el.type === "submit" || el.type === "button")) return el.value.trim();
    const txt = (el.textContent || "").replace(/\s+/g, " ").trim();
    return txt.slice(0, 80);
  }

  // ---------- selector generation (ranked, multi-candidate) ----------
  function getSelectors(el) {
    const sels = [];
    for (const attr of ["data-testid", "data-test", "data-cy", "data-qa"]) {
      const v = el.getAttribute(attr);
      if (v) sels.push({ type: "testid", value: `[${attr}="${esc(v)}"]`, score: 0.95 });
    }
    const role = implicitRole(el);
    const name = accName(el);
    if (role && name && name.length <= 60) {
      sels.push({ type: "aria", value: JSON.stringify({ role, name }), score: 0.9 });
    }
    if (name && ["button", "link"].includes(role)) {
      sels.push({ type: "text", value: name, score: 0.7 });
    }
    if (el.id && !looksAutoGenerated(el.id)) {
      sels.push({ type: "id", value: `#${esc(el.id)}`, score: 0.8 });
    }
    sels.push({ type: "css", value: cssPath(el), score: 0.3 });
    return sels.sort((a, b) => b.score - a.score);
  }

  function cssPath(el) {
    const parts = [];
    while (el && el.nodeType === 1 && el !== document.body) {
      if (el.id && !looksAutoGenerated(el.id)) { parts.unshift(`#${esc(el.id)}`); break; }
      let nth = 1, sib = el;
      while ((sib = sib.previousElementSibling)) if (sib.nodeName === el.nodeName) nth++;
      parts.unshift(`${el.nodeName.toLowerCase()}:nth-of-type(${nth})`);
      el = el.parentElement;
    }
    return parts.join(" > ");
  }

  // ---------- resolution (multi-selector fallback: first hit wins) ----------
  function resolveAria({ role, name }) {
    return Array.from(document.querySelectorAll("*"))
      .find((el) => implicitRole(el) === role && accName(el) === name) || null;
  }
  function resolveText(value) {
    return Array.from(document.querySelectorAll('button, a, [role="button"], input[type="submit"], summary'))
      .find((el) => accName(el) === value) || null;
  }
  function resolveStep(target) {
    for (const s of target.selectors) {
      let el = null;
      try {
        if (["testid", "id", "css"].includes(s.type)) el = document.querySelector(s.value);
        else if (s.type === "aria") el = resolveAria(JSON.parse(s.value));
        else if (s.type === "text") el = resolveText(s.value);
      } catch (_) {}
      if (el) return { el, via: s.type };
    }
    return { el: null };
  }
  async function waitForStep(target, timeout = 5000) {
    const start = Date.now();
    while (Date.now() - start < timeout) {
      const r = resolveStep(target);
      if (r.el && isVisible(r.el)) return r;
      await sleep(100);
    }
    return { el: null };
  }

  // ---------- the input actuator (the #1 silent killer) ----------
  function setNativeValue(el, value) {
    const proto = el instanceof HTMLTextAreaElement
      ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(proto, "value").set;
    setter.call(el, value);
    el.dispatchEvent(new InputEvent("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }

  // ---------- highlight overlay (the "watch it" feel) ----------
  function highlight(el) {
    const r = el.getBoundingClientRect();
    const box = document.createElement("div");
    Object.assign(box.style, {
      position: "fixed", left: r.left + "px", top: r.top + "px",
      width: r.width + "px", height: r.height + "px",
      border: "2px solid #e11", borderRadius: "3px", zIndex: 2147483647,
      pointerEvents: "none", boxShadow: "0 0 0 3px rgba(238,17,17,.25)",
      transition: "opacity .4s", opacity: "1",
    });
    document.documentElement.appendChild(box);
    setTimeout(() => { box.style.opacity = "0"; setTimeout(() => box.remove(), 400); }, 500);
  }

  // ---------- recording ----------
  let recording = false, steps = [], lastInputStep = null, lastInputEl = null;

  function humanLabel(action, el) {
    const name = accName(el) || el.nodeName.toLowerCase();
    return action === "input" ? `Type into "${name}"` : `Click "${name}"`;
  }
  function makeStep(action, el) {
    return { action, label: humanLabel(action, el), target: { selectors: getSelectors(el) } };
  }

  function onClick(e) {
    const el = e.target.closest('button,a,[role="button"],input,select,summary,[onclick]') || e.target;
    lastInputEl = lastInputStep = null;
    steps.push(makeStep("click", el));
  }
  function onInput(e) {
    const el = e.target;
    if (!isTextField(el)) return;
    if (lastInputEl === el && lastInputStep) { lastInputStep.value = el.value; return; }
    const step = makeStep("input", el); step.value = el.value;
    steps.push(step); lastInputStep = step; lastInputEl = el;
  }

  function startRecording() {
    steps = []; lastInputEl = lastInputStep = null; recording = true;
    document.addEventListener("click", onClick, true);
    document.addEventListener("input", onInput, true);
  }
  function stopRecording() {
    recording = false;
    document.removeEventListener("click", onClick, true);
    document.removeEventListener("input", onInput, true);
    return steps;
  }

  // ---------- replay ----------
  async function replay(stepList) {
    const results = [];
    for (let i = 0; i < stepList.length; i++) {
      const step = stepList[i];
      const r = await waitForStep(step.target);
      if (!r.el) {
        results.push({ i, ok: false, reason: `Could not find: ${step.label}` });
        return { ok: false, failedAt: i, results }; // fail with clear report
      }
      highlight(r.el);
      r.el.scrollIntoView({ block: "center", behavior: "instant" });
      await sleep(150);
      if (step.action === "click") r.el.click();
      else if (step.action === "input") setNativeValue(r.el, step.value);
      results.push({ i, ok: true, via: r.via });
      await sleep(300);
    }
    return { ok: true, results };
  }

  // ---------- popup messaging ----------
  chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
    if (msg.cmd === "start-record") { startRecording(); sendResponse({ ok: true }); }
    else if (msg.cmd === "stop-record") { sendResponse({ steps: stopRecording() }); }
    else if (msg.cmd === "status") { sendResponse({ recording, count: steps.length }); }
    else if (msg.cmd === "replay") { replay(msg.steps).then(sendResponse); return true; }
    return true;
  });
})();
