// Bao M0 spike — capture + deterministic replay on a single page.
// No LLM, no backend, no cross-navigation. Proves the risky core:
// selector generation, multi-selector fallback resolution, and the input actuator.

import type {
  AnchorDescriptor,
  Msg,
  Reach,
  ReplayResponse,
  Selector,
  Step,
  StepAction,
  StepResult,
  Target,
  WithinDescriptor,
} from "./types";

declare global {
  interface Window {
    __baoM0Loaded?: boolean;
  }
}

(() => {
  "use strict";

  // Idempotent: the manifest auto-injects this, but the harness may also inject
  // it programmatically (chrome.scripting) as a readiness fallback. Bail on a
  // second run so we don't register a duplicate onMessage listener.
  if (window.__baoM0Loaded) return;
  window.__baoM0Loaded = true;

  // ---------- shared helpers ----------
  const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
  const esc = (s: string) => (window.CSS && CSS.escape ? CSS.escape(s) : s.replace(/[^a-zA-Z0-9_-]/g, "\\$&"));

  function isTextField(el: Element): el is HTMLInputElement | HTMLTextAreaElement {
    return el instanceof HTMLTextAreaElement ||
      (el instanceof HTMLInputElement &&
        !["checkbox", "radio", "button", "submit", "file", "range"].includes(el.type));
  }

  function isVisible(el: Element): boolean {
    const r = el.getBoundingClientRect();
    if (r.width === 0 && r.height === 0) return false;
    const s = getComputedStyle(el);
    return s.visibility !== "hidden" && s.display !== "none";
  }

  // IDs like "ember123", ":r1:", "mui-3481", "radix-:r0:", uuids → unstable, skip.
  function looksAutoGenerated(id: string): boolean {
    return /\d{3,}/.test(id) || /[:]/.test(id) || /^[a-f0-9]{8}-/.test(id) || /^[a-z]+-?\d+$/i.test(id);
  }

  function implicitRole(el: Element): string | null {
    const tag = el.nodeName.toLowerCase();
    if (tag === "button") return "button";
    if (tag === "a" && el.hasAttribute("href")) return "link";
    if (tag === "select") return "combobox";
    if (tag === "textarea") return "textbox";
    if (tag === "input") {
      const t = (el.getAttribute("type") || "text").toLowerCase();
      if (["checkbox"].includes(t)) return "checkbox";
      if (["radio"].includes(t)) return "radio";
      if (["submit", "button"].includes(t)) return "button";
      return "textbox";
    }
    return el.getAttribute("role") || null;
  }

  // Approximate accessible name (good enough for M0).
  function accName(el: Element): string {
    const aria = el.getAttribute("aria-label");
    if (aria) return aria.trim();
    const placeholder = el.getAttribute("placeholder");
    if (placeholder) return placeholder.trim();
    const input = el as HTMLInputElement;
    if (input.labels && input.labels[0]) return (input.labels[0].textContent || "").trim();
    if (input.value && (input.type === "submit" || input.type === "button")) return input.value.trim();
    const txt = (el.textContent || "").replace(/\s+/g, " ").trim();
    return txt.slice(0, 80);
  }

  // ---------- selector generation (ranked, multi-candidate) ----------
  function getSelectors(el: Element): Selector[] {
    const sels: Selector[] = [];
    for (const attr of ["data-testid", "data-test", "data-cy", "data-qa"]) {
      const v = el.getAttribute(attr);
      if (v) sels.push({ type: "testid", value: `[${attr}="${esc(v)}"]`, score: 0.95 });
    }
    const role = implicitRole(el);
    const name = accName(el);
    if (role && name && name.length <= 60) {
      sels.push({ type: "aria", value: JSON.stringify({ role, name }), score: 0.9 });
    }
    if (name && role && ["button", "link"].includes(role)) {
      sels.push({ type: "text", value: name, score: 0.7 });
    }
    if (el.id && !looksAutoGenerated(el.id)) {
      sels.push({ type: "id", value: `#${esc(el.id)}`, score: 0.8 });
    }
    sels.push({ type: "css", value: cssPath(el), score: 0.3 });
    return sels.sort((a, b) => b.score - a.score);
  }

  function cssPath(el: Element): string {
    const parts: string[] = [];
    let node: Element | null = el;
    while (node && node.nodeType === 1 && node !== document.body) {
      if (node.id && !looksAutoGenerated(node.id)) { parts.unshift(`#${esc(node.id)}`); break; }
      let nth = 1, sib: Element | null = node;
      while ((sib = sib.previousElementSibling)) if (sib.nodeName === node.nodeName) nth++;
      parts.unshift(`${node.nodeName.toLowerCase()}:nth-of-type(${nth})`);
      node = node.parentElement;
    }
    return parts.join(" > ");
  }

  // ---------- shadow-DOM piercing (capture across OPEN shadow boundaries) ----------
  // A css path for `node` scoped to `root` (a Document or ShadowRoot). Walking
  // parentElement naturally stops at a shadow root's top child (whose parentElement is
  // null), so the path stays relative to the root the node actually lives in.
  function scopedCssPath(node: Element): string {
    const parts: string[] = [];
    let el: Element | null = node;
    while (el && el.nodeType === 1) {
      if (el.id && !looksAutoGenerated(el.id)) { parts.unshift(`#${esc(el.id)}`); break; }
      let nth = 1, sib: Element | null = el;
      while ((sib = sib.previousElementSibling)) if (sib.nodeName === el.nodeName) nth++;
      parts.unshift(`${el.nodeName.toLowerCase()}:nth-of-type(${nth})`);
      const parent: Element | null = el.parentElement;
      if (!parent || parent === document.body) break;
      el = parent;
    }
    return parts.join(" > ");
  }
  // The most stable selector for `node` that's unique *within its own root* — the
  // segment we use to hop one shadow boundary.
  function segmentSelector(node: Element, root: ParentNode): string {
    for (const attr of ["data-testid", "data-test", "data-cy", "data-qa"]) {
      const v = node.getAttribute(attr);
      if (v) { const sel = `[${attr}="${esc(v)}"]`; if (root.querySelectorAll(sel).length === 1) return sel; }
    }
    if (node.id && !looksAutoGenerated(node.id)) {
      const sel = `#${esc(node.id)}`; if (root.querySelectorAll(sel).length === 1) return sel;
    }
    return scopedCssPath(node);
  }
  // If `el` lives inside one or more OPEN shadow roots, return the ordered list of
  // per-boundary segment selectors (outermost host → … → el); null for light DOM.
  // Closed roots never reach here: composedPath stops at their host, so at capture
  // time we only ever hold light-DOM or open-shadow elements.
  function shadowSegments(el: Element): string[] | null {
    let root = el.getRootNode();
    if (!(root instanceof ShadowRoot)) return null;
    const segs: string[] = [];
    let node = el;
    while (root instanceof ShadowRoot) {
      segs.unshift(segmentSelector(node, root));
      node = root.host;
      root = node.getRootNode();
    }
    segs.unshift(segmentSelector(node, document)); // outermost host, in light DOM
    return segs;
  }
  // Resolve a shadow-piercing path by descending through each host's open shadow root.
  // Returns [el] or [] — the count-aware shape matchesOf expects.
  function resolveShadowPath(segs: string[]): HTMLElement[] {
    let ctx: ParentNode = document, el: HTMLElement | null = null;
    for (const seg of segs) {
      el = ctx.querySelector<HTMLElement>(seg);
      if (!el) return [];
      ctx = el.shadowRoot || el;
    }
    return el ? [el] : [];
  }
  // Classify how reachable a captured element is — drives graceful degrade. We only
  // ever see light or open-shadow leaves; an opaque custom element (hyphenated tag,
  // no open shadowRoot, no light children) is the closed-shadow tell, and <canvas> is
  // pixels. Both degrade (no clean selector) instead of recording a confident lie.
  function reachOf(el: Element): Reach {
    if (el.getRootNode() instanceof ShadowRoot) return "open-shadow";
    if (el.nodeName === "CANVAS") return "canvas";
    if (el.localName && el.localName.includes("-") && !el.shadowRoot && el.childElementCount === 0)
      return "opaque-custom";
    return "light";
  }

  // ---------- capture-time anchoring (escalate context until unique) ----------
  // Extract a *stable* token from an href: a note/comment id (`c-12345`), a post
  // slug (`/p/foo`), or any path segment carrying digits. Query-string junk and
  // session ids are skipped by preferring these shapes.
  function stableHrefId(href: string | null): string | null {
    if (!href) return null;
    const m = href.match(/c-\d+/) || href.match(/\/p\/[\w-]+/) || href.match(/\/[\w-]*\d[\w-]*/);
    return m ? m[0] : null;
  }
  // A selector that identifies a NODE by its own attributes, only if unique on page.
  function nodeUniqueSelector(node: Element): string | null {
    if (node.id && !looksAutoGenerated(node.id)) {
      const sel = `#${esc(node.id)}`;
      if (document.querySelectorAll(sel).length === 1) return sel;
    }
    for (const attr of ["data-testid", "data-test", "data-cy", "data-qa"]) {
      const v = node.getAttribute(attr);
      if (v) {
        const sel = `[${attr}="${esc(v)}"]`;
        if (document.querySelectorAll(sel).length === 1) return sel;
      }
    }
    return null;
  }
  // The smallest distinguishing signature inside `node`'s subtree: a unique link id.
  function uniqueHrefIn(node: Element): string | null {
    for (const a of node.querySelectorAll("a[href]")) {
      const id = stableHrefId(a.getAttribute("href"));
      if (id && document.querySelectorAll(`a[href*="${id.replace(/"/g, '\\"')}"]`).length === 1) return id;
    }
    return null;
  }
  // Last-resort signature for cards that carry no stable id/href (image-only
  // restacks, etc.): a short text fingerprint whose *exact* occurrences all live
  // inside `node` — i.e. unique to this card. Skips the target's own text and any
  // text it shares with sibling cards ("Like", "Reply", …).
  const normText = (el: Element) => (el.textContent || "").replace(/\s+/g, " ").trim();
  function uniqueTextIn(node: Element, leaf: Element): string | null {
    const seen = new Set<string>();
    for (const el of node.querySelectorAll("*")) {
      if (el === leaf || el.contains(leaf) || leaf.contains(el)) continue;
      const t = normText(el);
      if (t.length < 3 || t.length > 80 || seen.has(t)) continue;
      seen.add(t);
      const exact = Array.from(document.querySelectorAll("*")).filter((e) => normText(e) === t);
      if (exact.length && exact.every((e) => node.contains(e))) return t;
    }
    return null;
  }

  // Walk up from the target to the nearest ancestor we can pin down uniquely, and
  // describe the target *within* it. This is what turns an ambiguous "Share" into
  // "the Share button inside the card linking to c-276371955".
  function buildAnchor(leaf: Element): { node: Element; descriptor: AnchorDescriptor } | null {
    let node = leaf.parentElement;
    for (let hops = 0; node && node !== document.body && hops < 15; hops++, node = node.parentElement) {
      const sel = nodeUniqueSelector(node);
      if (sel) return { node, descriptor: { kind: "selector", value: sel } };
      const href = uniqueHrefIn(node);
      if (href) return { node, descriptor: { kind: "href", id: href } };
      const txt = uniqueTextIn(node, leaf);
      if (txt) return { node, descriptor: { kind: "text", id: txt } };
    }
    return null;
  }
  // The nearest scrollable ancestor — the viewport a virtualized list windows over.
  // Captured so replay can scroll-find a target that isn't yet in the DOM.
  function scrollableAncestor(el: Element): Element | null {
    for (let n = el.parentElement; n && n !== document.body; n = n.parentElement) {
      const s = getComputedStyle(n);
      if (/(auto|scroll)/.test(s.overflowY + s.overflow) && n.scrollHeight > n.clientHeight + 4) return n;
    }
    return null;
  }
  // A stable selector for a single node (id if usable, else a scoped css path).
  function nodeSelector(node: Element): string {
    if (node.id && !looksAutoGenerated(node.id) && document.querySelectorAll(`#${esc(node.id)}`).length === 1)
      return `#${esc(node.id)}`;
    return cssPath(node);
  }

  // A css path from `root` down to `leaf` (root exclusive). Stable while the card's
  // *internal* structure holds, even as the feed around it reorders.
  function relPath(root: Element, leaf: Element): string | null {
    const parts: string[] = [];
    let el: Element | null = leaf;
    while (el && el !== root && el.nodeType === 1) {
      let nth = 1, sib: Element | null = el;
      while ((sib = sib.previousElementSibling)) if (sib.nodeName === el.nodeName) nth++;
      parts.unshift(`${el.nodeName.toLowerCase()}:nth-of-type(${nth})`);
      el = el.parentElement;
    }
    return el === root ? parts.join(" > ") : null;
  }
  // A content-stable discriminator that singles `leaf` out from its same-named
  // siblings — its own attribute, independent of position.
  function refineWithin(matches: Element[], leaf: Element): { attr: string; value: string } | null {
    for (const attr of ["data-testid", "data-test", "data-cy", "data-qa", "title", "name", "href"]) {
      const v = leaf.getAttribute(attr);
      if (v && matches.filter((m) => m.getAttribute(attr) === v).length === 1) return { attr, value: v };
    }
    return null;
  }
  function describeWithin(anchorNode: Element, leaf: Element): WithinDescriptor {
    const role = implicitRole(leaf);
    const name = accName(leaf);
    const matches = allByWithin({ role, name }, anchorNode);
    const within: WithinDescriptor = { role, name, index: Math.max(0, matches.indexOf(leaf as HTMLElement)) };
    // Only when the role+name is itself ambiguous inside the card do we need a
    // tiebreak: a distinguishing attribute first, a structural path second.
    if (matches.length > 1) {
      const attr = refineWithin(matches, leaf);
      if (attr) within.attr = attr;
      const rel = relPath(anchorNode, leaf);
      if (rel) within.rel = rel;
    }
    return within;
  }

  // True iff selector `s` resolves to exactly the captured element (same path replay
  // will take). If no robust selector is unique, we must anchor.
  function resolvesUniquelyTo(s: Selector, el: Element): boolean {
    const m = matchesOf(s);
    return m.length === 1 && m[0] === el;
  }

  // T11: per-target grounding, captured on EVERY step. bbox viewport-relative (%),
  // plus the capture-time viewport pixels; text + aria role are healing fuel (unused at
  // replay today). (A sensitive step — T1, not yet landed — would omit `text`; inputs
  // carry no textContent anyway, so no value leaks through here today.)
  function bboxOf(el: Element): { x: number; y: number; w: number; h: number; vw: number; vh: number } {
    const r = el.getBoundingClientRect();
    const vw = Math.max(1, window.innerWidth), vh = Math.max(1, window.innerHeight);
    const pct = (n: number, d: number) => Math.round((n / d) * 1000) / 10;
    return { x: pct(r.left, vw), y: pct(r.top, vh), w: pct(r.width, vw), h: pct(r.height, vh), vw, vh };
  }
  function groundingOf(el: Element): Pick<Target, "bbox" | "text" | "role"> {
    return { bbox: bboxOf(el), text: normText(el).slice(0, 120), role: implicitRole(el) };
  }

  // The recorded target: leaf selectors, plus an anchor + within-descriptor whenever
  // the leaf alone can't be resolved back to the exact element.
  function getTarget(el: Element): Target {
    const reach = reachOf(el);
    const grounding = groundingOf(el);
    // Pixels (canvas) or an opaque custom element (likely closed shadow): we can't
    // build a clean selector. Grounding (bbox/text/role) is exactly the Tier-2/3 fuel
    // that lets these degrade honestly instead of recording a confident lie.
    if (reach === "canvas" || reach === "opaque-custom") {
      return { selectors: getSelectors(el), reach, ...grounding, unique: false, degraded: true };
    }
    const selectors = getSelectors(el);
    // Open-shadow leaf: prepend a shadow-piercing path so resolution can re-find it
    // (plain document.querySelector can't cross the boundary).
    const segs = shadowSegments(el);
    if (segs) selectors.unshift({ type: "shadowpath", value: JSON.stringify(segs), score: 0.92 });

    // A scrollable ancestor means the target may be virtualized off-screen at replay;
    // record the viewport so resolution can scroll-find it. (Additive — absent on
    // ordinary pages.)
    const sc = scrollableAncestor(el);
    const base: Omit<Target, "unique"> = { selectors, reach, ...grounding };
    if (sc) base.scroll = { container: nodeSelector(sc) };

    const robustUnique = selectors.some((s) => s.type !== "css" && resolvesUniquelyTo(s, el));
    if (robustUnique) return { ...base, unique: true };

    const anchor = buildAnchor(el);
    if (anchor) {
      const within = describeWithin(anchor.node, el);
      return { ...base, anchor: anchor.descriptor, within, unique: true };
    }
    return { ...base, unique: false }; // best-effort: brittle css path only
  }

  // ---------- count-aware resolution ----------
  // Every resolver returns ALL matches (optionally scoped to a root subtree) so the
  // caller can reason about ambiguity instead of blindly taking the first hit — the
  // root cause of the "wrong item in a repeated list" bug.
  function allByAria({ role, name }: { role: string; name: string }, root: ParentNode = document): HTMLElement[] {
    return Array.from(root.querySelectorAll<HTMLElement>("*"))
      .filter((el) => implicitRole(el) === role && accName(el) === name);
  }
  function allByText(value: string, root: ParentNode = document): HTMLElement[] {
    return Array.from(root.querySelectorAll<HTMLElement>('button, a, [role="button"], input[type="submit"], summary'))
      .filter((el) => accName(el) === value);
  }
  function matchesOf(s: Selector, root: ParentNode = document): HTMLElement[] {
    try {
      if (s.type === "shadowpath") return resolveShadowPath(JSON.parse(s.value));
      if (["testid", "id", "css"].includes(s.type)) return Array.from(root.querySelectorAll<HTMLElement>(s.value));
      if (s.type === "aria") return allByAria(JSON.parse(s.value), root);
      if (s.type === "text") return allByText(s.value, root);
    } catch (_) {}
    return [];
  }
  // A selector "within" the anchor subtree: role+name, picked by recorded index.
  function allByWithin({ role, name }: { role: string | null; name?: string }, root: ParentNode): HTMLElement[] {
    return Array.from(root.querySelectorAll<HTMLElement>("*"))
      .filter((el) => implicitRole(el) === role && (!name || accName(el) === name));
  }

  // ---------- anchor resolution (the robust path for repeated lists) ----------
  // Re-find the anchor's stable "seed" (a unique id'd container, or a unique link/
  // text deeper in the card), then climb to the smallest ancestor that actually
  // contains the target — content-anchored, so it survives feed reorders.
  function anchorSeed(a: AnchorDescriptor): Element | null {
    if (a.kind === "selector") return document.querySelector(a.value);
    if (a.kind === "href") return document.querySelector(`a[href*="${a.id.replace(/"/g, '\\"')}"]`);
    if (a.kind === "text") {
      const all = Array.from(document.querySelectorAll("*"));
      // Prefer an element whose exact text IS the fingerprint; fall back to any
      // element containing it. Smallest wins so the seed lands deep in one card.
      const exact = all.filter((el) => normText(el) === a.id);
      const pool = exact.length ? exact : all.filter((el) => (el.textContent || "").includes(a.id));
      return pool.sort((x, y) => (x.textContent || "").length - (y.textContent || "").length)[0] || null;
    }
    return null;
  }
  function resolveViaAnchor(target: Target): HTMLElement | null {
    const seed = anchorSeed(target.anchor!);
    if (!seed) return null;
    const within = target.within!;
    let node: Element | null = seed;
    for (let i = 0; i < 15 && node; i++) {
      const m = allByWithin(within, node);
      if (m.length) {
        if (m.length === 1) return m[0];
        // Collision inside the anchor: content-stable attribute beats structural
        // path beats raw positional index.
        if (within.attr) {
          const hit = m.find((el) => el.getAttribute(within.attr!.attr) === within.attr!.value);
          if (hit) return hit;
        }
        if (within.rel) { try { const r = node.querySelector<HTMLElement>(within.rel); if (r) return r; } catch (_) {} }
        return m[within.index] || m[0];
      }
      node = node.parentElement;
    }
    return null;
  }

  interface Resolution {
    el: HTMLElement | null;
    via?: string;
  }

  function resolveStep(target: Target): Resolution {
    // 1) Anchor-scoped resolution wins — it's the only path that disambiguates one
    //    "Copy link" from its 20 identical siblings.
    if (target.anchor && target.within) {
      const el = resolveViaAnchor(target);
      if (el) return { el, via: "anchor" };
    }
    // 2) Plain selectors, but PREFER a uniquely-resolving one over first-of-many.
    //    A selector that matches the whole list must not outrank a precise one just
    //    because its `type` scores high.
    let ambiguous: Resolution | null = null;
    for (const s of target.selectors) {
      const m = matchesOf(s);
      if (m.length === 1) return { el: m[0], via: s.type };
      if (m.length > 1 && !ambiguous) ambiguous = { el: m.find(isVisible) || m[0], via: `${s.type}~ambiguous` };
    }
    return ambiguous || { el: null };
  }
  // "Good enough to commit to." A first-of-many ambiguous match never is. And when
  // the target carried an anchor (it was ambiguous at capture), only an anchor hit is
  // trustworthy — a unique css/positional match is exactly the recycled-row lie that
  // virtualization creates, so it must not preempt the anchor.
  function isGood(r: Resolution, target: Target): r is Resolution & { el: HTMLElement } {
    if (!r.el || !isVisible(r.el)) return false;
    if (String(r.via || "").includes("ambiguous")) return false;
    if (target.anchor && r.via !== "anchor") return false;
    return true;
  }

  // Scroll the captured viewport top-to-bottom, re-resolving after each step, until
  // the anchor pins the target. Only an anchor hit stops the scan (off-screen rows
  // resolve to whatever's on screen). Linear scan is the honest fallback; a
  // uniform-row binary search is a later optimization.
  async function scrollFind(target: Target): Promise<Resolution> {
    const c = document.querySelector(target.scroll!.container);
    if (!c) return { el: null };
    const step = Math.max(64, c.clientHeight * 0.7);
    const restore = c.scrollTop;
    for (let y = 0, i = 0; y <= c.scrollHeight && i < 3000; y += step, i++) {
      c.scrollTop = y;
      await sleep(30); // let the windowed list render the new slice
      const r = resolveStep(target);
      if (isGood(r, target)) return r;
    }
    c.scrollTop = restore;
    return { el: null };
  }
  async function waitForStep(target: Target, timeout = 5000): Promise<Resolution> {
    const start = Date.now();
    while (Date.now() - start < timeout) {
      const r = resolveStep(target);
      if (isGood(r, target)) return r;
      // Off-screen in a virtualized list: scroll-find before settling for anything.
      if (target.scroll) {
        const sr = await scrollFind(target);
        if (sr.el) return sr;
      }
      if (r.el && isVisible(r.el)) return r; // last resort: a unique-but-imperfect hit
      await sleep(100);
    }
    return { el: null };
  }

  // ---------- the input actuator (the #1 silent killer) ----------
  function setNativeValue(el: HTMLInputElement | HTMLTextAreaElement, value: string): void {
    const proto = el instanceof HTMLTextAreaElement
      ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(proto, "value")!.set!;
    setter.call(el, value);
    el.dispatchEvent(new InputEvent("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }
  // Native <select>: option list is OS-drawn, so set value + fire the events the page
  // listens for (frameworks key off `change`).
  function setSelectValue(el: HTMLSelectElement, value: string): void {
    el.value = value;
    el.dispatchEvent(new Event("input", { bubbles: true }));
    el.dispatchEvent(new Event("change", { bubbles: true }));
  }
  // contenteditable actuator. setNativeValue can't drive these — there is no value
  // setter. Attempt order: (1) execCommand insertText (deprecated, but still the only
  // synthetic path most editors accept — it routes through the same cancelable
  // beforeinput a real keystroke produces, so model-driven editors like ProseMirror/
  // Lexical apply it to their model); (2) synthetic beforeinput+input dispatch;
  // (3) verify the text landed, else report failure. Heavily custom editors (Google
  // Docs is canvas anyway) may reject all synthetic paths — the honest failure is
  // correct behavior, not a bug.
  const squish = (s: string) => (s || "").replace(/\s+/g, " ").trim();
  async function setEditableValue(el: HTMLElement, value: string): Promise<boolean> {
    const landed = () => squish(el.innerText).includes(squish(value));
    el.focus();
    try {
      document.execCommand("selectAll", false, undefined);
      document.execCommand("insertText", false, value);
    } catch (_) {}
    await sleep(50);
    if (landed()) return true;
    try {
      el.dispatchEvent(new InputEvent("beforeinput", {
        bubbles: true, cancelable: true, inputType: "insertText", data: value,
      }));
      el.dispatchEvent(new InputEvent("input", {
        bubbles: true, inputType: "insertText", data: value,
      }));
    } catch (_) {}
    await sleep(50);
    return landed();
  }

  // ---------- highlight overlay (the "watch it" feel) ----------
  function highlight(el: Element): void {
    const r = el.getBoundingClientRect();
    const box = document.createElement("div");
    Object.assign(box.style, {
      position: "fixed", left: r.left + "px", top: r.top + "px",
      width: r.width + "px", height: r.height + "px",
      border: "2px solid #e11", borderRadius: "3px", zIndex: 2147483647,
      pointerEvents: "none", boxShadow: "0 0 0 3px rgba(238,17,17,.25)",
      transition: "opacity .4s", opacity: "1",
    });
    document.documentElement.appendChild(box);
    setTimeout(() => { box.style.opacity = "0"; setTimeout(() => box.remove(), 400); }, 500);
  }

  // ---------- recording ----------
  let recording = false;
  let steps: Step[] = [];
  let lastInputStep: Step | null = null;
  let lastInputEl: Element | null = null;
  let lastStepUrl: string | null = null;

  // SPA soft-navigation marker (T7). Rich SaaS apps route via history.pushState —
  // the content script survives (no teardown), so we detect the route change by
  // comparing location.href step-over-step and insert a synthetic marker the replay
  // can wait on. urlPattern wildcards digit runs: the id minted at record time is
  // not the id at replay time ("create then open" flows).
  function urlPatternOf(u: string): string {
    return u.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\d+/g, "\\d+");
  }
  function markSoftNav(): void {
    if (location.href === lastStepUrl) return;
    const marker: Step = {
      action: "softNav", label: `Route changed to ${location.href}`,
      urlAfter: location.href, urlPattern: urlPatternOf(location.href),
      frame: frameInfo(), ts: Date.now(),
    };
    steps.push(marker); syncStep(marker);
    lastStepUrl = location.href;
  }
  function pushStep(step: Step): void { markSoftNav(); steps.push(step); syncStep(step); }

  // M1: stream every step to the SW as it happens — a full-document navigation
  // destroys this script and its page-memory buffer, so the durable trace lives in
  // chrome.storage.session, SW-side. Coalesced input steps re-send under the same
  // seq and the SW replaces in place. Fire-and-forget: when no SW-side recording
  // session is active (M0 single-page flows), the SW ignores these.
  let stepSeq = 0;
  const seqPrefix = Math.random().toString(36).slice(2, 8); // per-frame uniqueness
  function syncStep(step: Step): void {
    if (!step.seq) step.seq = `${seqPrefix}-${++stepSeq}`;
    try { chrome.runtime.sendMessage({ cmd: "bao-step", step }).catch(() => {}); } catch (_) {}
  }

  // The only keys we capture (T4). General typing is owned by onInput; this whitelist
  // is the submit/commit/dismiss set. code === key for all three; keyCode kept for the
  // odd handler that still reads it.
  const KEYS: Record<string, { code: string; keyCode: number }> = {
    Enter: { code: "Enter", keyCode: 13 },
    Escape: { code: "Escape", keyCode: 27 },
    Tab: { code: "Tab", keyCode: 9 },
  };

  function humanLabel(action: StepAction, el: Element, key?: string): string {
    const name = accName(el) || el.nodeName.toLowerCase();
    if (action === "input") return `Type into "${name}"`;
    if (action === "select") return `Choose an option in "${name}"`;
    if (action === "setChecked") return `Set "${name}"`;
    if (action === "keypress") return `Press ${key || "key"} in "${name}"`;
    if (action === "submit") return `Submit "${name}"`;
    return `Click "${name}"`;
  }
  // Which frame this step was captured in. The content script runs per-frame
  // (all_frames), so a cross-origin child records its own steps relative to its own
  // document; the SW stitches frames together by frameId at stop time.
  function frameInfo() {
    return { url: location.href, origin: location.origin, top: window === window.top };
  }
  // `target` is precomputed only for T5 (grabbed at pointerdown, before the node could
  // unmount); otherwise resolve it now against the live element.
  function makeStep(action: StepAction, el: Element, target?: Target, key?: string): Step {
    const now = Date.now();
    return {
      action, label: humanLabel(action, el, key), target: target ?? getTarget(el),
      frame: frameInfo(), ts: now,
      meta: { viewport: { w: window.innerWidth, h: window.innerHeight }, recordedAt: now }, // T11
    };
  }

  // The real interactive element, piercing OPEN shadow boundaries. `event.target` is
  // retargeted to the shadow host; `composedPath()` exposes the true inner node and
  // its ancestors across roots, so we pick the nearest interactive one.
  const INTERACTIVE = 'button,a,[role="button"],input,select,textarea,summary,[onclick]';
  function composedLeaf(e: Event): Element {
    const path = e.composedPath ? e.composedPath() : [e.target];
    for (const n of path) {
      if (n instanceof Element && n.matches && n.matches(INTERACTIVE)) return n;
    }
    return path[0] instanceof Element ? path[0] : (e.target as Element);
  }

  // T5: the target of a click can unmount before `click` fires (menus that close on
  // mousedown, rows that re-render). Capture it at pointerdown — while the node is
  // still alive — and commit either from onClick (normal) or from onPointerUp (when the
  // node vanished, since Chromium then dispatches no click at all). `flushed` guards
  // against a double-emit if a click somehow still follows a pointerup commit.
  let pending: { leaf: Element; target: Target; ts: number; flushed: boolean } | null = null;
  let pendingTimer: ReturnType<typeof setTimeout> | null = null;
  function onPointerDown(e: Event): void {
    if (!recording) return;
    const leaf = composedLeaf(e);
    pending = { leaf, target: getTarget(leaf), ts: Date.now(), flushed: false };
    if (pendingTimer) clearTimeout(pendingTimer);
    pendingTimer = setTimeout(() => { pending = null; }, 500); // drags/text-selection leave no click
  }
  // If the pointerdown target unmounted before a click could fire (verified: Chromium
  // dispatches NO click when the mousedown target is removed), commit the step here so
  // it isn't silently lost — using the target we grabbed while the node was alive.
  function onPointerUp(): void {
    if (!recording || !pending || pending.flushed) return;
    if (!pending.leaf.isConnected) { pending.flushed = true; commitClick(pending.leaf, pending.target); }
  }

  // T3: the checkbox/radio a click ultimately toggles — directly, or via its <label>.
  function checkableFrom(el: Element): HTMLInputElement | null {
    if (el instanceof HTMLInputElement && (el.type === "checkbox" || el.type === "radio")) return el;
    const label = el.closest?.("label") as HTMLLabelElement | null;
    const ctrl = label?.control;
    if (ctrl instanceof HTMLInputElement && (ctrl.type === "checkbox" || ctrl.type === "radio")) return ctrl;
    return null;
  }

  // T4: remember the last action that could cause a form submit, so onSubmit can tag
  // it `submits:true` and drop the redundant bare `submit` step.
  let submitCause: { step: Step; form: HTMLFormElement; ts: number } | null = null;
  function noteSubmitCause(step: Step, el: Element): void {
    const form = (el as HTMLInputElement).form || el.closest?.("form") || null;
    if (form instanceof HTMLFormElement) submitCause = { step, form, ts: Date.now() };
  }

  function commitClick(leaf: Element, target?: Target): void {
    lastInputEl = lastInputStep = null;
    const step = makeStep("click", leaf, target);
    noteSubmitCause(step, leaf); // T4: this click may be what submits the form
    pushStep(step);
  }
  function onClick(e: Event): void {
    const clickLeaf = composedLeaf(e);
    // T6: assert-mode — the click marks an expectation, it doesn't perform the action.
    // Swallow it (no navigation/submit) and record a textPresent assertion by default.
    if (assertArmed) {
      assertArmed = false; pending = null;
      e.preventDefault(); e.stopImmediatePropagation();
      const step = makeStep("assert", clickLeaf);
      const value = normText(clickLeaf).slice(0, 120);
      step.assert = { kind: "textPresent", value };
      step.label = `Expect: "${value}"`;
      pushStep(step);
      return;
    }
    if (clickLeaf.nodeName === "SELECT") return; // captured via change, not click
    const p = pending; pending = null;
    if (p && p.flushed) return;                  // onPointerUp already emitted this gesture (T5)
    // Adopt the pointerdown capture on the same leaf (saves a re-resolve) or when the
    // captured node vanished and the click retargeted to an ancestor.
    const adopt = p && (p.leaf === clickLeaf || !p.leaf.isConnected) ? p : null;
    const leaf = adopt ? adopt.leaf : clickLeaf;

    // T3: a DIRECT click on a checkbox/radio → record its END-STATE (replayed as SET,
    // not toggle). A click that reaches the control only through its <label> is
    // ignored: the browser synthesizes a second click on the control itself, which we
    // record instead — otherwise the label + control clicks double-record.
    const directBox = leaf instanceof HTMLInputElement && (leaf.type === "checkbox" || leaf.type === "radio") ? leaf : null;
    if (!directBox && checkableFrom(leaf)) return;
    if (directBox) {
      lastInputEl = lastInputStep = null;
      const step = makeStep("setChecked", directBox);
      pushStep(step);
      // The click handler sees pre-activation checkedness (reverted if something
      // preventDefaults); read the settled value on the next task.
      setTimeout(() => { step.checked = directBox.checked; syncStep(step); }, 0);
      return;
    }
    commitClick(leaf, adopt ? adopt.target : undefined);
  }
  // T6: Alt+Shift+A arms assert-mode — the next click captures an expectation instead
  // of an action. Keyed off code+modifiers (Alt on macOS mangles e.key).
  let assertArmed = false;
  // T4: whitelisted keys only — Enter (submit/commit), Escape (dismiss), Tab (commit).
  function onKeyDown(e: KeyboardEvent): void {
    if (!recording) return;
    if (e.altKey && e.shiftKey && e.code === "KeyA") { assertArmed = true; return; } // T6
    if (!KEYS[e.key]) return;
    const el = composedLeaf(e);
    const step = makeStep("keypress", el, undefined, e.key);
    step.key = e.key;
    pushStep(step);
    if (e.key === "Enter") noteSubmitCause(step, el); // Enter-implicit submit
  }
  // T4: covers Enter-implicit and button-implicit submits uniformly. If a click/Enter
  // we just recorded caused this submit, tag it and drop the bare step; otherwise the
  // submit was JS-triggered with no recorded cause, so record it against the form.
  function onSubmit(e: Event): void {
    if (!recording) return;
    const form = e.target;
    if (!(form instanceof HTMLFormElement)) return;
    const c = submitCause;
    submitCause = null;
    if (c && c.form === form && Date.now() - c.ts < 200) {
      c.step.submits = true; syncStep(c.step);
      return;
    }
    pushStep(makeStep("submit", form));
  }
  // The editable ROOT the event belongs to. Editors nest contenteditable nodes, so
  // walk to the highest contentEditable ancestor — that's the stable, addressable
  // surface (the leaf under the caret churns per keystroke).
  function editableRoot(node: EventTarget | null | undefined): HTMLElement | null {
    const start = node instanceof Element ? node : node instanceof Node ? node.parentElement : null;
    if (!(start instanceof HTMLElement) || !start.isContentEditable) return null;
    let el: HTMLElement = start;
    while (el.parentElement && el.parentElement.isContentEditable) el = el.parentElement;
    return el;
  }
  // Coalesced contenteditable capture: one step per editable root per typing burst,
  // value = innerText (we replay semantics, not markup).
  function recordEditable(root: HTMLElement): void {
    if (!recording) return;
    const value = root.innerText;
    if (lastInputEl === root && lastInputStep) { lastInputStep.value = value; syncStep(lastInputStep); return; }
    const step = makeStep("input", root);
    step.mode = "contenteditable"; step.value = value;
    pushStep(step); lastInputStep = step; lastInputEl = root;
  }
  function onInput(e: Event): void {
    const el = e.composedPath ? e.composedPath()[0] : e.target;
    const root = editableRoot(el);
    if (root) { recordEditable(root); return; }
    if (!(el instanceof Element) || !isTextField(el)) return;
    if (lastInputEl === el && lastInputStep) { lastInputStep.value = el.value; syncStep(lastInputStep); return; }
    const step = makeStep("input", el); step.value = el.value;
    pushStep(step); lastInputStep = step; lastInputEl = el;
  }
  // Strict model-driven editors (Lexical-style) preventDefault their beforeinput and
  // mutate the DOM themselves — so no native `input` event ever fires. Capture via
  // beforeinput too, reading the root's text on the next tick, after the editor (or
  // the browser default) has applied the change. recordEditable coalesces, so the
  // overlap with onInput on ordinary editables is harmless.
  function onBeforeInput(e: Event): void {
    const root = editableRoot(e.composedPath ? e.composedPath()[0] : e.target);
    if (!root) return;
    setTimeout(() => recordEditable(root), 0);
  }
  function onChange(e: Event): void {
    const el = e.composedPath ? e.composedPath()[0] : e.target;
    if (!(el instanceof HTMLSelectElement)) return;
    const step = makeStep("select", el); step.value = el.value;
    pushStep(step); lastInputEl = lastInputStep = null;
  }

  function startRecording(): void {
    steps = []; lastInputEl = lastInputStep = null; lastStepUrl = location.href;
    pending = null; submitCause = null; assertArmed = false; recording = true;
    document.addEventListener("pointerdown", onPointerDown, true);
    document.addEventListener("pointerup", onPointerUp, true);
    document.addEventListener("click", onClick, true);
    document.addEventListener("input", onInput, true);
    document.addEventListener("beforeinput", onBeforeInput, true);
    document.addEventListener("change", onChange, true);
    document.addEventListener("keydown", onKeyDown, true);
    document.addEventListener("submit", onSubmit, true);
  }
  function stopRecording(): Step[] {
    markSoftNav(); // a route change after the last step still gets its marker
    recording = false;
    document.removeEventListener("pointerdown", onPointerDown, true);
    document.removeEventListener("pointerup", onPointerUp, true);
    document.removeEventListener("click", onClick, true);
    document.removeEventListener("input", onInput, true);
    document.removeEventListener("beforeinput", onBeforeInput, true);
    document.removeEventListener("change", onChange, true);
    document.removeEventListener("keydown", onKeyDown, true);
    document.removeEventListener("submit", onSubmit, true);
    // Report this frame's steps to the SW so it can merge them with sibling/child
    // frames (which the top frame can't see across an origin boundary). Best-effort.
    if (steps.length) {
      try { chrome.runtime.sendMessage({ cmd: "bao-frame-steps", steps }).catch(() => {}); } catch (_) {}
    }
    return steps;
  }

  // ---------- replay ----------
  // Wait for a recorded soft navigation to settle: the URL must match the recorded
  // pattern (digit runs wildcarded — replay-time ids differ) before the next step's
  // element resolution starts, instead of leaning on the generic 5s retry.
  async function waitForUrl(step: Step, timeout = 5000): Promise<boolean> {
    let re: RegExp | null = null;
    try { re = new RegExp(`^${step.urlPattern}$`); } catch (_) {}
    const matches = () => (re ? re.test(location.href) : location.href === step.urlAfter);
    const start = Date.now();
    while (Date.now() - start < timeout) {
      if (matches()) return true;
      await sleep(100);
    }
    return matches();
  }
  // T6: poll until the target is gone or hidden (elementAbsent inverts waitForStep).
  async function assertAbsent(target: Target, timeout = 3000): Promise<boolean> {
    const start = Date.now();
    while (Date.now() - start < timeout) {
      const r = resolveStep(target);
      if (!r.el || !isVisible(r.el)) return true;
      await sleep(100);
    }
    return false;
  }
  // T6: poll until location.href matches (regex if `value` compiles, else substring).
  async function assertUrl(value: string, timeout = 5000): Promise<boolean> {
    let re: RegExp | null = null;
    try { re = new RegExp(value); } catch (_) {}
    const matches = () => (re ? re.test(location.href) : location.href.includes(value));
    const start = Date.now();
    while (Date.now() - start < timeout) {
      if (matches()) return true;
      await sleep(100);
    }
    return matches();
  }
  // T6: evaluate one expectation. Never acts on the page; returns pass/fail + detail.
  async function evalAssert(step: Step): Promise<{ ok: boolean; detail: string }> {
    const a = step.assert!;
    if (a.kind === "urlMatches") {
      const ok = await assertUrl(a.value ?? "");
      return { ok, detail: location.href };
    }
    if (a.kind === "elementAbsent") {
      const ok = step.target ? await assertAbsent(step.target) : true;
      return { ok, detail: ok ? "absent" : "still present" };
    }
    if (a.kind === "elementVisible") {
      const r = step.target ? await waitForStep(step.target) : { el: null };
      return { ok: !!r.el, detail: r.el ? "visible" : "not found" };
    }
    // textPresent — page-wide: the text must appear somewhere in the rendered body.
    const want = squish(a.value ?? "");
    const start = Date.now();
    while (Date.now() - start < 5000) {
      if (squish(document.body.innerText).includes(want)) return { ok: true, detail: "found" };
      await sleep(100);
    }
    return { ok: false, detail: `"${want}" not on page` };
  }

  async function replay(stepList: Step[]): Promise<ReplayResponse> {
    const results: StepResult[] = [];
    for (let i = 0; i < stepList.length; i++) {
      const step = stepList[i];
      // T6: assertions are checked, never acted on, and are NON-FATAL — a failed
      // expectation is recorded and replay continues so the runner reports them all.
      if (step.action === "assert") {
        const { ok, detail } = await evalAssert(step);
        results.push({ i, ok, via: `assert:${step.assert!.kind}`, reason: ok ? undefined : `Expected ${step.assert!.kind} ${JSON.stringify(step.assert!.value)} — ${detail}` });
        continue;
      }
      // Full-document navigate markers are SW-owned (the RunState machine waits on
      // webNavigation, not on this script — which the nav destroys). If one reaches
      // the in-page replayer (M0 single-page path), it's a no-op.
      if (step.action === "navigate" || step.action === "waitForUser") {
        results.push({ i, ok: true, via: "noop (SW-owned step)" });
        continue;
      }
      if (step.action === "softNav") {
        const ok = await waitForUrl(step);
        if (!ok) {
          results.push({ i, ok: false, reason: `Route never matched ${step.urlAfter} (now: ${location.href})` });
          return { ok: false, failedAt: i, results };
        }
        results.push({ i, ok: true, via: "softNav" });
        continue;
      }
      // Degraded capture (canvas / closed shadow): no clean selector exists. Fail
      // cleanly rather than guess — this is where a Tier-3/4 executor takes over.
      if (!step.target || step.target.degraded) {
        const reach = step.target ? step.target.reach : "unknown";
        results.push({ i, ok: false, reason: `Needs escalation (reach=${reach}): ${step.label}` });
        return { ok: false, failedAt: i, results };
      }
      const r = await waitForStep(step.target);
      if (!r.el) {
        results.push({ i, ok: false, reason: `Could not find: ${step.label}` });
        return { ok: false, failedAt: i, results }; // fail with clear report
      }
      let el = r.el;
      el.scrollIntoView({ block: "center", behavior: "instant" });
      await sleep(150);
      // Virtualized lists recycle nodes on scroll, so the node we resolved may now
      // render *different* data after scrollIntoView settles. Re-resolve via the
      // content anchor so we act on the node that currently shows the target.
      if (step.target.scroll && r.via === "anchor") {
        const rr = resolveStep(step.target);
        if (isGood(rr, step.target)) el = rr.el;
      }
      highlight(el);
      if (step.action === "click") el.click();
      else if (step.action === "input" && step.mode === "contenteditable") {
        const landed = await setEditableValue(el, step.value ?? "");
        if (!landed) {
          results.push({ i, ok: false, reason: `Editor rejected synthetic input: ${step.label}` });
          return { ok: false, failedAt: i, results };
        }
      }
      else if (step.action === "input") setNativeValue(el as HTMLInputElement | HTMLTextAreaElement, step.value ?? "");
      else if (step.action === "select") setSelectValue(el as HTMLSelectElement, step.value ?? "");
      // T3: drive to the recorded state, don't blindly toggle. A real click keeps
      // framework handlers happy; only fall back to setting .checked if it didn't take.
      else if (step.action === "setChecked") {
        const box = el as HTMLInputElement;
        const want = step.checked === true;
        if (box.checked !== want) {
          box.click();
          if (box.checked !== want) { box.checked = want; box.dispatchEvent(new Event("change", { bubbles: true })); }
        }
        if (box.checked !== want) {
          results.push({ i, ok: false, reason: `Could not set checkbox: ${step.label}` });
          return { ok: false, failedAt: i, results };
        }
      }
      // T4: synthetic keys are isTrusted:false — they won't trigger the browser's
      // implicit form submit, so for a submit-causing key we requestSubmit() unless the
      // dispatch already submitted (a page that listens on keydown Enter).
      else if (step.action === "keypress") {
        const key = step.key || "Enter";
        const info = KEYS[key] || { code: key, keyCode: 0 };
        // keyCode/which can't be set via the constructor init (ignored → 0); the
        // whitelist keys are all read via key/code by any modern handler.
        const opts: KeyboardEventInit = { key, code: info.code, bubbles: true, cancelable: true };
        const form = (el as HTMLInputElement).form || el.closest?.("form") || null;
        let submitted = false;
        const onSub = () => { submitted = true; };
        if (step.submits && form) form.addEventListener("submit", onSub, { once: true, capture: true });
        el.dispatchEvent(new KeyboardEvent("keydown", opts));
        el.dispatchEvent(new KeyboardEvent("keyup", opts));
        if (step.submits && form) {
          await sleep(50);
          form.removeEventListener("submit", onSub, true);
          if (!submitted) { try { form.requestSubmit(); } catch (_) { form.submit(); } }
        }
      }
      // T4: a bare submit with no recorded click/Enter cause (JS-triggered at record).
      else if (step.action === "submit") {
        if (el instanceof HTMLFormElement) { try { el.requestSubmit(); } catch (_) { el.submit(); } }
      }
      results.push({ i, ok: true, via: r.via });
      await sleep(300);
    }
    // Actions early-return on failure; reaching here means every action passed, so the
    // run is ok iff no non-fatal assertion (T6) failed.
    const failed = results.find((res) => !res.ok);
    return failed ? { ok: false, failedAt: failed.i, results } : { ok: true, results };
  }

  // ---------- popup messaging ----------
  chrome.runtime.onMessage.addListener((msg: Msg, _sender, sendResponse) => {
    if (msg.cmd === "start-record") { startRecording(); sendResponse({ ok: true }); }
    else if (msg.cmd === "stop-record") { sendResponse({ steps: stopRecording() }); }
    else if (msg.cmd === "status") { sendResponse({ recording, count: steps.length }); }
    else if (msg.cmd === "replay") { replay(msg.steps).then(sendResponse); return true; }
    return true;
  });

  // ---------- M1 boot handshake ----------
  // Every fresh document announces itself to the SW once it's ready to be acted on
  // (readyState complete — acting earlier misses not-yet-rendered targets). The SW
  // rehydrates from storage and answers: re-arm recording mid-trace, or resume a
  // paused run's state machine. Both the SW and this script are disposable; storage
  // is the only memory.
  function bootPing(): void {
    try {
      chrome.runtime.sendMessage({ cmd: "bao-boot", url: location.href, top: window === window.top })
        .then((res) => { if (res && res.record && !recording) startRecording(); })
        .catch(() => {});
    } catch (_) {}
  }
  if (document.readyState === "complete") bootPing();
  else window.addEventListener("load", bootPing, { once: true });
})();
